### Registro de nuevo usuario (JUGADOR por defecto)
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "ejemplo@gamehub.com",
  "password": "12345678a",
  "nombre": "Ejemplo Usuario"
}


### Registro ADMIN
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "administrador@gamehub.com",
  "password": "12345678a",
  "nombre": "Administrador",
  "rol": "admin"
} 


### LOG ejemplo JUGADOR)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ejemplo@gamehub.com",
  "password": "12345678a"
}


#### LOG ADMIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@gamehub.com",
  "password": "12345678a"
}

