
@token = eyJhbGciOiJIUzI1NiIsImtpZCI6Ik9tOFVCeHBsblhsTTc5T2siLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2ZwZ3FhYW9paWVibWNwdHd6ZWxlLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3MTQ1MzIxZi1mZmI3LTQ2NzgtODNhZS03NDFhMGJjZWE1NTgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUwMjg5OTEwLCJpYXQiOjE3NTAyODYzMTAsImVtYWlsIjoiYWRtaW5AZ2FtZWh1Yi5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiYWRtaW5AZ2FtZWh1Yi5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI3MTQ1MzIxZi1mZmI3LTQ2NzgtODNhZS03NDFhMGJjZWE1NTgifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1MDI4NjMxMH1dLCJzZXNzaW9uX2lkIjoiMjRlZWE1YTgtZGI2Yi00OWM5LWJkM2MtMDJiNGZhNDNlYTJjIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.tJuu0eXIK6rsuAL38r4X8Tu5FUplKIjZ70cKGAW9IxQ

###
POST http://localhost:3000/user-games/adquirirJuego
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "game_id": "fc38551b-470a-43cb-a15e-8c11ab09ba66"
}
