
@token = eyJhbGciOiJIUzI1NiIsImtpZCI6Ik9tOFVCeHBsblhsTTc5T2siLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2ZwZ3FhYW9paWVibWNwdHd6ZWxlLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhZmJlZDZkNC0wZGFlLTQwMDctODhiYS0zYjAyZmU4YzYzMjQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUwMjAxMTY5LCJpYXQiOjE3NTAxOTc1NjksImVtYWlsIjoiZWplbXBsb0BnYW1laHViLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJlamVtcGxvQGdhbWVodWIuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiYWZiZWQ2ZDQtMGRhZS00MDA3LTg4YmEtM2IwMmZlOGM2MzI0In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NTAxOTc1Njl9XSwic2Vzc2lvbl9pZCI6IjE4ZWQ3MTFjLWM0ZWEtNDA4Ny1hN2FlLTZjNzg1NTUyMGY2YSIsImlzX2Fub255bW91cyI6ZmFsc2V9.JeRun0f-_tNg3XlArbASV3p93Ix1KiIj98EUsYS4-uE

###
POST http://localhost:3000/user-games/adquirirJuego
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "game_id": "fc38551b-470a-43cb-a15e-8c11ab09ba66"
}
